(function(){var g=void 0,i=true,l=null,m=false,n,o=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b){function c(){}c.prototype=b.prototype;a.M=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ca(){}
function da(a,b,c){switch(typeof b){case "string":ea(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),da(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],typeof f!="function"&&(c.push(d),ea(e,c),c.push(":"),da(a,f,c),d=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var fa={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ga=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ea(a,b){b.push('"',a.replace(ga,function(a){if(a in fa)return fa[a];var b=a.charCodeAt(0),e="\\u";b<16?e+="000":b<256?e+="00":b<4096&&(e+="0");return fa[a]=e+b.toString(16)}),'"')};var ha={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function ia(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function ja(a,b){var c="",d=ka(encodeURIComponent(a));d.splice(b||5,d.length);p(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ka(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,h=3285377520,j=[],k,t,w,D,E,T=Math.ceil((a.length/4+2)/16),P=[T],y=0,v;y<T;y++){P[y]=[];for(k=0;k<16;k++)P[y][k]=a.charCodeAt(y*64+k*4)<<24|a.charCodeAt(y*64+k*4+1)<<16|a.charCodeAt(y*64+k*4+2)<<8|a.charCodeAt(y*64+k*4+3)}y=(a.length-1)*8;a=T-1;P[a][14]=Math.floor(y/Math.pow(2,32));P[a][15]=y&4294967295;for(y=0;y<T;y++){for(v=0;v<16;v++)j[v]=P[y][v];
for(v=16;v<80;v++)j[v]=(j[v-3]^j[v-8]^j[v-14]^j[v-16])<<1|(j[v-3]^j[v-8]^j[v-14]^j[v-16])>>>31;a=c;k=d;t=e;w=f;D=h;for(v=0;v<80;v++)E=Math.floor(v/20),E=(a<<5|a>>>27)+(E==0?k&t^~k&w:E==1?k^t^w:E==2?k&t^k&w^t&w:k^t^w)+D+b[E]+j[v]&4294967295,D=w,w=t,t=k<<30|k>>>2,k=a,a=E;c=c+a&4294967295;d=d+k&4294967295;e=e+t&4294967295;f=f+w&4294967295;h=h+D&4294967295}return[c,d,e,f,h]}
function la(a){var b=o.navigator,c=o.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];p(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=o.performance;d=d.concat([b&&b.now?b.now():"",document.title,o.location.href,q(),ia()]);return d.concat(a||[]).join()}function r(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function s(a){return typeof a!=="undefined"}function u(a){return a&&a.replace(/^www\./,"")}var ma=/^((https?\:)?(\/\/))/i;function na(a){return a&&a.replace(ma,"")}var oa=/^((https?\:)?(\/\/))?[^\/]*/;function pa(a){return a.replace(oa,"")}var qa=/\#.*/;function ra(a){return a.replace(qa,"")}var sa=/\?[^\#]*/;function ta(a){return a.toLowerCase()}var ua=/\/+((\?|\#).*)?$/;function va(a){return a.replace(ua,"$1")}function wa(a){return a&&a.replace(sa,"")}
function xa(a){var b=a.match(/\?(.*)$/ig)?a.match(/\?(.*)$/ig)[0].slice(1).replace(/#(.*)?/ig,"").split("&"):[],c=a.match(/#(.*)$/ig)?a.match(/#(.*)$/ig)[0]:"",a=a.match(/[#|\?](.*)?/ig)?a.slice(0,a.search(/[#|\?](.*)?/ig)):a,b=ya(b,function(a){return a.search("utm")!==0});b.length>0&&(a+="?"+b.join("&"));return a+c}function za(a,b){if(a===b)return 0;var c=l;p([ta,va,na,pa,ra,wa],function(d,e){a=d(a);b=d(b);if(a===b)return c=e+1,m});return c}
function x(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function Aa(a,b){var c=o;c.removeEventListener?c.removeEventListener(a,b,m):c.detachEvent&&c.detachEvent("on"+a,b)}function Ba(a){return typeof a==="number"}function z(a){return typeof a==="string"}function Ca(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function q(){return(new Date).getTime()}function Da(){return o.location.protocol==="http:"?"http:":"https:"}
function Ea(a){return!!a&&a.constructor===Object}function p(a,b){if(Ea(a)===i)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===m)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===m)break}}function Fa(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function ya(a,b){var c=[];p(a,function(a){b(a)&&c.push(a)});return c}
function Ga(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,h=a.length;f<=h;f++)c[0][f]=f;for(var j,k,t,d=1;d<=e;d++)for(f=1;f<=h;f++)j=d-1,k=f-1,t=c[j][k],b.charAt(j)==a.charAt(k)?c[d][f]=t:(k=c[d][k]+1,j=c[j][f]+1,t+=2,c[d][f]=Math.min(k,j,t));return c[b.length][a.length]}var Ha;function Ia(){}var Ja=o.setInterval,Ka=o.clearInterval,La=o.setTimeout,Ma=o.clearTimeout;
function Na(a){switch(a){case g:return"undefined";case "":return"empty";default:return a}};function Oa(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace(/\+/g," "),p(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Pa(a,b){var c="",d=o.location.href.match(/[^?]+[?]([^#]+).*/);if(d){var d=Oa(d[1]),e=b||a;d[e]&&(c=d[e])}return encodeURIComponent(c)}function Qa(a,b){return!b?i:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Ra(a){var b=[];p(Sa,function(c){var d=a[c];s(d)&&(Object.prototype.toString.call(d)==="[object Array]"?p(d,function(a){b.push(c+"="+a)}):Ea(d)?p(d,function(a,c){b.push(c+"="+a)}):((d+"").length||c=="r")&&b.push(c+"="+d))});b.push("_");return b.join("&")}
function Ta(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=o.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=Qa(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?
"/"+a:e.substr(0,f)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Qa(b.protocol,b.port)||b.port==="0")b.port="";return b}
function Ua(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function Va(a,b,c,d){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+(a+(d?'="'+d+'"':""))+"]");for(var e=[],b=c.getElementsByTagName(b),c=b.length,f="";c--;)(f=b[c].getAttribute(a))&&(!d||f===d)&&e.push(b[c]);return e}function Wa(a,b,c){c=c||"";if(a===g)a=m;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?m:Wa(a.parentNode,b,c)}return a}
function Xa(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=Va("data-cb-scroll-element"))&&c.length)return c[0][b];if(Ba(o[a]))return o[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function Ya(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}
function Za(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function $a(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return l;var d=a.ownerDocument.documentElement,e=0,f=s(c)?c+1:-1;z(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return l}
function ab(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function bb(a){a=a||window.event;return!a?l:$a(a.target||a.srcElement,ab,10)}function cb(a,b){var c=document.createElement(a);p(b,function(a,b){c.setAttribute(b,a)});return c};function db(){this.G={};this.Ua=1}function A(a,b,c,d){a.Ua++;a.G[b]=a.G[b]||{};a.G[b][a.Ua]=[c,d];return a.Ua}function eb(a,b){if(z(b))a.G[b]=g,delete a.G[b];else if(Ba(b)){var c=i;p(a.G,function(a){p(a,function(e,f){if(parseInt(f,10)===b)return a[f]=g,delete a[f],c=m});return c})}}db.prototype.Q=function(a,b){if(this.G[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];p(this.G[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
db.prototype.addEventListener=function(a,b){var c=A(this,a,b);b._cbEventId=c};db.prototype.removeEventListener=function(a,b){this.G[a]&&this.G[a][b._cbEventId]&&this.G[a][b._cbEventId][0]===b&&eb(this,b._cbEventId)};var B=new db,fb="a";var C={};
C.D=function(){C.Ha?C.sa("pageload"):(C.xb=[{target:o,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:o,event:"resize"},{target:document.body,event:"mousedown"}],C.Aa=l,C.$=l,C.Ga={},C.hb={},p(C.xb,function(a){var b=a.event;x(a.target,b,function(a){C.sa.call(C,b,a)})}),A(B,"f",function(){C.sa("focus")}),C.sa("pageload"),x(document.body,"click",function(a){(a=bb(a))&&B.Q("c",a)},i),x(document.body,"contextmenu",function(a){(a=bb(a))&&B.Q("r",
a)}),C.Ha=i)};C.Cb=function(){var a,b=C.hb.keydown;if(b===g)return m;b=q()-b;return b<=(a||15E3)&&b>=0};C.Xa=100;C.sa=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}C.mc(a);if(C.Aa===l)C.rb(a);else if(!C.$||ha[C.$]<ha[a])C.$=a};C.mc=function(a){C.hb[a]=q()};C.rb=function(a){C.Aa=La(C.Hb,C.Xa);B.Q(fb);C.Ga[a]!==l&&Ma(C.Ga[a]);C.dc(a)};
C.dc=function(a){var b=C.Ga;b[a]=La(function(){Ma(b[a]);delete b[a];var c=m;p(b,function(){c=i;return m});c||B.Q("i")},ha[a]+C.Xa)};C.Hb=function(){Ma(C.Aa);C.Aa=l;if(C.$)C.rb(C.$),C.$=l};var gb,hb,ib,jb,kb;(function(){var a,b;p(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof o.document[a]==="boolean")return b=c,m});b!==g&&(jb=a,kb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),ib=b+"visibilitychange")})();var F=m;function lb(){F=kb&&o.document[kb]==="prerender"?i:m}function mb(){hb=i;B.Q("f")}function nb(){hb=m;B.Q("b")}
function ob(a,b,c){o.addEventListener?o.addEventListener(a,c,m):o.document.attachEvent&&o.document.attachEvent(b,c)}function pb(){var a=i;o.document.hasFocus&&(a=o.document.hasFocus());var b=m;jb&&(b=o.document[jb]);return a&&!b}function qb(){pb()?mb():nb()}function rb(a){lb();if(F){var b=m,c=function(){b||(lb(),F||(b=i,a(),o.window.setTimeout(function(){o.document.removeEventListener(ib,c,m)},100)))};o.document.addEventListener(ib,c,m)}else a()};function G(){this.a=o._sf_async_config||{};this.bb=r(this.lb,this)}G.prototype.D=function(){this.mb=0};G.prototype.lb=function(){};G.prototype.wa=function(a){if(!F){var b=this.bb,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};G.prototype.na=function(){this.bb=l};var H="path",I="domain",sb="useCanonical",tb="useCanonicalDomain",J="title",ub="virtualReferrer";function K(a,b,c){a[b]=a[b]||c}function vb(a,b){for(var c=o[a]||[];c.length;)b(c.shift());o[a]={push:b}}function wb(a){p(document.getElementsByTagName("script"),function(b){if(typeof b.src==="string"&&b.src.match(/chartbeat.js/))return b=Oa(b.src.split("?")[1]),K(a,"uid",b.uid),K(a,I,b.domain),m})}function xb(a,b){return a[b]?encodeURIComponent(a[b]):""}
function yb(a){var b={};p(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};var L={};L.Fb=function(a){try{L.create("_cb_test","1",1,a);var b=L.k("_cb_test");L.remove("_cb_test",a);return b==="1"}catch(c){return m}};L.k=function(a){a+="=";var b="";p(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),m});return b};
L.create=function(a,b,c,d){var e=o._sf_async_config;if(e&&e.noCookies)return"";e=new Date;e.setTime(q()+c*1E3);a=a+"="+b+("; expires="+e.toGMTString())+("; path="+d);return document.cookie=a};L.remove=function(a,b){return L.k(a)?L.create(a,"",-86400,b):""};var M={};M.B=function(a){var b=o._sf_async_config;if(!a&&b&&b.noCookies)return l;if(M.B.Da!==g)return M.B.Da;var a=q()+"",c,d;try{if((d=o.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return M.B.Da=d}catch(e){}return M.B.Da=l};M.k=function(a){var b=M.B();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&q()>c)?(M.remove(a),""):b.getItem(a)||""};
M.create=function(a,b,c){var d=M.B();if(d){var e=new Date;e.setTime(q()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};M.remove=function(a){var b=M.B();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function zb(a,b){this.va=a||"";this.N=b||"/";this.Ib=M.B()!==l||L.Fb(this.N);this.Ta=m;Ab(this)}n=zb.prototype;n.isSupported=function(){return this.Ib};
function Ab(a){if(!L.k("_cb_ls")){var b=M.B()!==l,c=L.k("_SUPERFLY_lockout");c&&p(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,i)});var d=L.k("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,i),L.remove("_chartbeat3",a.N));b&&((b=L.k("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,i),(b=L.k("_chartbeat5"))&&a.create("_chartbeat5",b,60,i));L.create("_cb_ls","1",34128E3,a.N)}}
n.create=function(a,b,c,d){a=d?a:this.va+a;(M.B()?M:L).create(a,b,c,this.N);M.B()&&L.create(a,b,c,this.N)};n.update=function(a,b,c,d,e,f,h){a=d?a:this.va+a;e=z(e)?e:"::";d=(d=this.k(a,i))?d.split(e):[];if(h&&d.length){var j=h(b),k=Fa(d,function(a){return h(a)===j});k!==-1&&d.splice(k,1)}d.push(b);for(Ba(f)&&d.length>f&&d.splice(0,d.length-f);d.length>1&&d.join(e).length>4E3;)d.shift();this.create(a,d.join(e),c,i)};
n.k=function(a,b){var a=b?a:this.va+a,c=(M.B()?M:L).k(a);if(!c&&M.B()&&(c=L.k(a))&&L.k("_cb_ls")){this.Ta=i;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}M.create(a,c,d)}return c};n.remove=function(a,b){a=b?a:this.va+a;(M.B()?M:L).remove(a,this.N);M.B()&&L.remove(a,this.N)};function Bb(a){var b=l;if(a&&(b=Cb(),b=!b?b:N(b.pathname)+b.search+b.hash))return b;var c=o.location,b=N(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Db(a){return a&&(a=Cb(),a=!a?a:a.hostname)?a:o.location.hostname}function Cb(){var a=Eb();return!a?a:Ta(a.href)}
function Eb(){var a=l;p(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return a=b,m});return a}for(var Fb={},Gb=0;Gb<81;Gb++)Fb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Gb)]=i;function Hb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Fb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}
function N(a){if(!z(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Hb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function O(a,b){var c=Q();return s(b)&&!s(c[a])?b:c[a]}function Q(){s(o._cb_shared)||(o._cb_shared={});return o._cb_shared};var R={zb:{IDLE:0,yc:1,rc:2,yb:3},J:0};R.D=function(){if(!R.Ha)A(B,fb,R.Ob,R),A(B,"i",R.Rb,R),A(B,"f",R.Qb,R),A(B,"b",R.Pb,R),R.Ha=i};R.Mb=function(){return R.J};R.Ob=function(){R.J===1?R.P(3):R.J===0&&R.P(2)};R.Rb=function(){R.J===3?R.P(1):R.J===2&&R.P(0)};R.Qb=function(){(R.J===0||R.J===2)&&R.P(3)};R.Pb=function(){R.J===3?R.P(2):R.J===1&&R.P(0)};R.P=function(a){R.J=a;B.Q("s",a)};function Ib(a,b){this.Fa=a||g;this.Ma=b||g;this.ea=this.ba=0;this.Ub=r(this.Vb,this);this.tb=this.aa=l}n=Ib.prototype;n.D=function(){this.ea=this.ba=0;this.aa=l;this.tb=A(B,"s",this.fb,this);this.fb(R.Mb())};n.fb=function(a){Ka(this.aa);this.aa=l;if(a===R.zb.yb)this.aa=Ja(this.Ub,1E3)};n.Vb=function(){if(this.Fa===g||this.Fa())this.ba++,this.ea++,this.Ma&&this.Ma()};n.terminate=function(){Ka(this.aa);this.aa=l;eb(B,this.tb)};n.na=function(){this.terminate();this.Ma=this.Fa=g};function S(){G.call(this);this.S=[];this.q=new zb(this.ic,this.a.cookiePath||"/");this.q.remove("_SUPERFLY_nosample");this.F=new Ib;this.Na=r(this.ua,this);x(o,"unload",this.Na);rb(r(this.D,this));this.Ia=m}ba(S,G);n=S.prototype;n.Ra=i;
n.D=function(){S.M.D.call(this);this.pa=this.U=0;this.ja=q();this.Qa=ja(Jb(this));this.Pa=i;this.Ja=72E5;if(this.Ra){var a=+this.a.sessionLength;if(!isNaN(a))this.Ja=a*6E4}a=O("d");if(!a){var a=[],b=this.q.k("_chartbeat2",i);b.length>0&&(a=b.split("."));a.length>6&&(a=[]);var b=q(),c=this.q.k("_cb",i);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var d=b-+(a[1]||0),e=b-+(a[2]||0);Q().n=c&&d>18E5&&e<2592E6?0:1;var d=a[4],f=parseInt(a[5],10)||0;if(!(e=e>18E5))if(Kb(this))e=m;else{var e=U(this),e=decodeURIComponent(e),
e=Lb(e)||e,h;h=Mb(this);h=decodeURIComponent(h);h=Lb(h)||h;e=e!==h}!d||e?(d=ja(Jb(this)),a[4]=d,f=1,this.q.remove("_cb_svref",i)):f+=1;a[5]=f;f="1";e=a&&+a[2];d=a&&a[3];if(a&&e&&d)if(f=Math.abs((Ca(b)-Ca(e))/864E5)){f=Math.min(f,16)-1;for(e="";f--;)e+=0;f=(d+e+"1").slice(-16)}else f=d;d=f;c||(c=this.a.utoken||ja(Jb(this),3),a[1]=b);a[2]=b;a[3]=d;this.a.utoken=this.la;this.q.create("_cb",c,34128E3,i);this.q.create("_chartbeat2",a.join("."),34128E3,i);a[0]=c;Q().d=a}this.Bc=a.join(".");var j;c=+a[1];
d=+a[2];if((b=a[3])&&c&&d)j=(Math.min((Math.abs((Ca(d)-Ca(c))/864E5)||0)+1,16,b.length)-1).toString(16),j+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.eb=j;this.Yb=O("n",1);this.la=a[0];this.hc=a[4];this.fc=a[5];this.gc=Mb(this);this.q.create("_cb_svref",Mb(this)||"null",1800,i);this.F.D();R.D();C.D();gb||(hb=pb(),ib&&o.document.addEventListener&&o.document.addEventListener(ib,qb,m),ob("focus","onfocusin",mb),ob("blur","onfocusout",nb),hb&&mb(),gb=i);this.fa=0;this.Bb=A(B,fb,this.$b,this)};
function Nb(a){if(!a.q.k("_SUPERFLY_lockout")&&!F)a.Wb?a.xa():(a.Wb=i,!o._sf_async_config&&!o._cbq?(a.ta=r(a.xa,a),x(o,"load",a.ta)):a.xa())}n.xa=function(){this.Oa=Ob();C.D();var a=r(this.ga,this);this.gb=Ja(a,15E3);this.ga()};
n.ga=function(){var a=this.F.ea,a=this.a.reading&&+this.a.reading||a>0;if(this.pa<this.U&&!a)this.pa++;else{var b;if(Ha===g)b=o.navigator.userAgent,Ha=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Ha;b&&!a?this.pa++:(a?this.U=0:Pb(this),this.pa=0,this.S.push(0),this.S.length>18&&this.S.shift(),this.Ra&&q()-this.ja>=this.Ja?this.terminate():this.ia())}};
n.lb=function(){this.S.push(1);var a=0;p(this.S,function(b){a+=b});a<3?(this.Pa=i,Pb(this)):(this.terminate(),this.q.create("_SUPERFLY_lockout","1",600))};n.ua=function(){};n.$b=function(){var a=Qb(this);this.fa=Math.max(this.fa,a)};function Qb(a){return Math.floor(Xa("Y","Top",!!a.a.scrollElement))}function Pb(a){var b=a.U,b=b?Math.min(b*2,16):1;a.U=b}n.oa=function(){this.ua();this.terminate()};n.ya=function(){this.Ia=i;this.D();Nb(this)};
function Kb(a){if(a.a[ub])return i;if(Rb(a))return m;a=document.referrer.indexOf("://"+o.location.hostname+"/");return a!=-1&&a<9}function Rb(a){var b=a.a.referrerOverrideQueryParam,c="";p(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),m});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}
function U(a){a=a.a[ub]||Rb(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=Ta(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=N(b.pathname),a=Ua(b)}return encodeURIComponent(a)}function Sb(a){a=a.a[J].slice(0,100);return encodeURIComponent(a)}function Jb(a){a=[U(a),Za("Width"),Za("Height")];return la(a)}function Tb(a){var b=[],c=a.q.k("_chartbeat4");c&&(p(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.q.remove("_chartbeat4"));return b}
function Mb(a){a=a.q.k("_cb_svref",i)||U(a)||"null";a==="null"&&(a="");return a}function Lb(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?l:a[1]}function Ob(){var a=o.performance&&o.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return Ba(b)&&b?Ba(a)&&a>b?a-b:q()-b:-1}n.terminate=function(){this.F.terminate();eb(B,this.Bb);this.ta!==g&&Aa("load",this.ta);Ka(this.gb);Q().d=g;Q().n=g};
n.na=function(){this.terminate();Aa("unload",this.Na);this.Na=this.ta=this.q=this.S=this.a=l;this.F.na();this.F=l;S.M.na.call(this)};function Ub(a){for(var b=O("m")||[];b.length;)a(b.shift());a={push:a};Q().m=a};function Vb(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=Wb(a);d+=f.x;e+=f.y;for(var h=m,j=c?0:Math.floor(Xa("X","Left",g)),k=c?0:Math.floor(Xa("Y","Top",g)),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=Wb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(Xb(a,["position"]).position==="fixed"){h=i;break}a=a.parentElement}c||(d-=b?b.scrollLeft:j,e-=b?b.scrollTop:k);h&&(d+=j,e+=k);return{x:d,y:e}}
function Xb(a,b){var c={},d,e;o.getComputedStyle?d=o.getComputedStyle(a,l):a.currentStyle?e="currentStyle":a.style&&(e="style");p(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var Yb=/matrix(3d)?\((.*)\)/;function Wb(a){var b={x:0,y:0},a=Xb(a,["transform"]).transform;if(!z(a))return b;var c=a.match(Yb);if(!c)return b;var a=c[2].split(", "),d;s(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};function Zb(){var a=o.location.href,a=a.replace(/-{2,}/g,"-"),a=Ta(a);a.pathname=N(a.pathname);return a}
function $b(a){var b=L.k("_chartbeat6");if(!b)return l;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=Zb(),h=Ua(f);p(b,function(a,b){var f=a.split(","),k=Ga(h,decodeURIComponent(f[0]));if(k===0)return c=f,d=b,m;if(e===g||k<e)e=k,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+ac(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),f=decodeURIComponent(c[1]),j=c[2];c.splice(0,3);for(var k=c.length/3,t=0;t<k;t++){var w=t*3+2;a.push({zc:b,origin:f,X:j,Z:w<c.length?
c[w]:"",Jb:c[t*3],oc:c[t*3+1]})}return a}function ac(a){var b="",c;if(!Ea(a))return b;a.jb&&(c=new Date,c.setTime(c.getTime()+a.jb),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function bc(a){var b=a.topStorageDomain,a=a[I],c=o.location.hostname;return b?b:cc(c,a)?a:c.replace(/^www\./,"")}
function cc(a,b){if(a===b)return i;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return m;if(c.pop()!==d.pop())return m}return i}function dc(a,b,c,d,e){this.Lb=a;this.Kb=b;this.pc=c;this.X=d;this.Z=e}function ec(a){var b=a.d,c=l;if(b!==l){var d={};b.s&&p(b.s,function(a,b){d[b]=typeof a==="string"?{Za:a,Z:""}:{Za:a.chosenVariant,Z:a.specificLocation}});c={qb:d,X:b.g,ib:b.m}}return{status:a.s,data:c,code:a.c,message:a.m}};function fc(a,b){for(var c=b||document.documentElement,d=[],e=l,f=a,h,j,k,t,w,D;f&&f!==c;){h=f.nodeName.toLowerCase();e=f;j=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){k=f.children;t=0;for(w=0,D=k.length;w<D;w++){if(e===k[w]){h+="["+(1+w-t)+"]";break}k[w].nodeName!==j&&t++}}d.unshift(h)}return d.join("/")};function V(){this.ic="_t_";this.ab=this.sb=Ia;S.call(this)}ba(V,S);n=V.prototype;
n.D=function(){V.M.D.call(this);wb(this.a);var a=!!this.a[sb],b=Db(!!this.a[tb]&&a);K(this.a,"mabServer","mabping.chartbeat.net");K(this.a,J,document.title);K(this.a,I,b);this.a[H]=this.a[H]?N(this.a[H]):Bb(a);this.da=u(b);this.a[I]=u(this.a[I]);this.lc=bc(this.a);this.ca=this.qa=m;this.cb=[];var c=this,a=$b({domain:"."+this.lc,jb:6E4,path:"/"});if(a!==l)this.qa=i,p(a,function(a){c.cb.push(new dc(a.origin,a.Jb,a.oc,a.X,a.Z))});this.kb=0;this.za=l;Ub(r(this.Tb,this))};
n.ia=function(){var a=this.F.ba,b=gc(this),c,d=this;this.qa&&p(this.cb,function(e){c=b+"&x="+e.Kb+"&v="+e.pc+"&ml="+e.X+"&xo="+e.Lb+"&e="+a+"&sl="+e.Z;d.wa(c)});!this.ca&&this.za&&hc(this,this.za);this.ca=i};n.xa=function(){this.Oa=Ob();C.D();if(this.qa){var a=r(this.ga,this);this.gb=Ja(a,500)}this.ga()};n.ga=function(){var a,b;this.ca?(a=this.F.ba,b=this.kb*15,a-b>=15&&(this.ia(),this.kb+=1),a>=45&&this.terminate()):this.ia()};
function gc(a){var b=a.a;return Da()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b[I])+"&p="+encodeURIComponent(b[H])+"&d="+encodeURIComponent(a.da)+"&u="+a.la+"&c="+Math.round((q()-a.ja)/600)/100}n.ua=function(){};n.jc=function(a){a=ec(a);this.ca?hc(this,a):this.za=a};
function hc(a,b){var c=gc(a),d=b.status,e=b.data;if(d=="s"&&e!==l){var f=r(a.wa,a);Ea(e.qb)&&p(e.qb,function(a,b){f(c+"&x="+b+"&v="+a.Za+"&ml="+e.X+"&sl="+a.Z+"&e=-1")});Object.prototype.toString.call(e.ib)==="[object Array]"&&p(e.ib,function(a){f(c+"&me=3&ml="+e.X+"&x="+a)})}else d=="e"&&a.wa(c+"&me="+b.code)}
n.Tb=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],e=a.shift();e==="t"?this.jc.apply(this,a):e==="v"?this.pb.apply(this,a):e==="sv"?this.ec.apply(this,a):e==="ev"&&this.pb.apply(this,a)}};n.oa=function(){this.ab();V.M.oa.call(this)};n.ya=function(){Q().m=[];this.sb();V.M.ya.call(this)};n.ec=function(a){this.sb=a};n.pb=function(a){this.ab=a};n.terminate=function(){this.Ac=g;this.za=l;this.ca=this.qa=g;V.M.terminate.call(this)};if(!L.k("cb_optout")&&!o.pSUPERFLY_mab){var ic=new V,jc={};jc.evps=r(ic.oa,ic);jc.svps=r(ic.ya,ic);o.pSUPERFLY_mab=jc;Nb(ic)};var kc="engagedSeconds",lc={wc:"id",vc:kc,sc:"campaignId",tc:"creativeId",xc:"placementId",uc:"element"};var mc,nc,W;
function oc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);pc();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=s(g)?g:{},b.src=a,a=cb("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],s(g)?g.appendChild(a):b&&b.appendChild(a)}}
function pc(){Ma(nc);nc=g;Aa("message",oc);W&&W.parentNode&&W.parentNode.removeChild(W);W=g};function qc(){var a=o._sf_async_config&&o._sf_async_config.domain;if(a&&!mc){mc=i;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);x(o,"message",oc);nc=La(pc,1E4);var b=s(g)?g:{};b.src=a;a=cb("iframe",b);a.style.display="none";s(g)?g.appendChild(a):document.body&&document.body.appendChild(a);W=a}}
function rc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=M.B(i),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),qc(),Aa("message",rc))}};function sc(a,b){this.wb=b;this.vb=a[sb];this.ub=a[tb];this.O=a[H];this.kc=a[J];this.$a=a[I];this.qc=a[ub];this.Ya=(this.H=Cb())?this.H.hostname:"";this.ma=this.H?N(this.H.pathname)+this.H.search+this.H.hash:"";this.ob=Bb(m);this.cc=Db(m);var c=Va("property","meta",l,"og:url");this.ha=(this.Y=c&&c.length?Ta(c[0].content):l)?N(this.Y.pathname)+this.Y.search+this.Y.hash:"";this.Zb=this.Y?this.Y.hostname:"";this.Ea=document.title||"";var d;if((c=Va("property","meta",l,"og:title"))&&c.length)d=c[0].content;
this.ra=d;var e;if((d=Va("property","meta",l,"twitter:title"))&&d.length)e=d[0].content;this.ka=e;e=!!this.vb;d=this.vb!==g;var c=!!this.ub,f=this.ub!==g,h=!!this.H,j;j=u(this.Ya);var k=u(this.cc);j=j===k;var k=!!this.ha,t=!this.H?m:this.ma===this.ha,w=this.ma===this.ob,D;D=this.ma;var E=wa(this.ob);D=D===E;var E=!!this.Ea,T=!!this.ra,P=!!this.ka,y=this.Ea===this.ra,v=!this.ka?m:this.Ea===this.ka,Ac=!this.ra||!this.ka?m:this.ra===this.ka,Bc=!!this.kc,Cc=!!this.O,Dc=this.O?this.O.charAt(0)!=="/":m,
Ec=!this.H?m:this.O===this.ma,Fc=!this.ha?m:this.O===this.ha,Gc=!this.H?m:this.$a===u(this.Ya),Hc=!this.ha?m:this.$a===u(this.Zb),Ic=!!this.wb,Jc=this.wb?m:!!this.qc,Kc=Da()==="https:",Lc=!!XMLHttpRequest,Z;this.O?(Z=xa(this.O),Z=Z!==wa(Z)):Z=m;e=[e,d,c,f,h,j,k,t,w,D,E,T,P,y,v,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Z];d=1;for(f=c=0;f<e.length;f++)c|=e[f]&&d,d<<=1;this.Gb=("00000000"+c.toString(16)).slice(-8)};function X(){"postMessage"in window&&x(o,"message",r(this.Sb,this));S.call(this);vb("_cbq",r(this.nb,this))}ba(X,S);
X.prototype.D=function(){X.M.D.call(this);var a=this.la;Q().u=a;a=this.Qa;Q().t=a;this.Xb=new sc(this.a,this.Ia);this.Ca=l;wb(this.a);var a=!!this.a[sb],b=Db(!!this.a[tb]&&a);K(this.a,"pingServer","ping.chartbeat.net");K(this.a,J,document.title);K(this.a,I,b);this.a[H]=this.a[H]?N(this.a[H]):Bb(a);this.da=u(b);this.a[I]=u(this.a[I]);this.Db=A(B,"c",this.ac,this);this.Eb=A(B,"r",this.bc,this);this.T=l};X.prototype.Ab=function(a){this.Ca=a};
X.prototype.ua=function(){this.q.update("_chartbeat4",["t="+this.Qa,"E="+this.F.ba,"x="+Qb(this),"c="+Math.round((q()-this.ja)/600)/100,"y="+Za("Height"),"w="+Ya("Height")].join("&"),60,g,g,1)};var Sa="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_x,_y,_z,_s,t,V,z,i,L,tz,l,,sn,C,sv,sr,sd,im".split(",");n=X.prototype;
n.ia=function(a){this.mb++;var b={};b.g=this.a.uid;b.g0=xb(this.a,"sections");b.g1=xb(this.a,"authors");b.g2=xb(this.a,"zone");b.g3=xb(this.a,"sponsorName");b.g4=xb(this.a,"type");!this.a.noCookies&&this.q.isSupported()?b.n=this.Yb:b.nc=1;b.c=Math.round((q()-this.ja)/600)/100;b.E=this.F.ba;var c=Qb(this);this.fa=Math.max(this.fa,c);b.x=c;b.m=this.fa;b.y=Za("Height");b.o=Za("Width");b.w=Ya("Height");b.b=this.Oa>0?this.Oa:"";if(this.eb)b.f=this.eb;b[""]=yb(this.a);b.t=this.Qa;b.V=106;b.tz=(new Date).getTimezoneOffset();
b.sn=this.mb;b.sv=this.hc;b.sr=this.gc;b.sd=this.fc;c=this.F.ea;b.h=encodeURIComponent(this.a[I]);b.p=encodeURIComponent(this.a[H]);b.u=this.la;b.d=encodeURIComponent(this.da);b.j=Math.round((this.U+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;C.Cb()?b.W=1:this.a.reading&&+this.a.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Kb(this);if(this.Pa){this.Pa=m;if(c)this.T=tc(this);b.i=Sb(this);var d=this.a.hudTrackable;d!==g&&(b.L=d?"1":"0");this.a.alias&&(b.PA=encodeURIComponent(this.a.alias))}if(c){if(this.T){if(b.v=
encodeURIComponent(this.T.path),b.K=uc(this.T),this.T.La>1)b.l1=this.T.La}else b.v=U(this);this.Ia&&(b.vp=1)}else b.r=U(this);c=Na(b.v);Q().v=c;c=Na(b.r);Q().r=c;b.A=this.Ca?this.Ca:"";b._c=Pa("utm_campaign",this.a.campaignTag);b._m=Pa("utm_medium",this.a.mediumTag);b._x=Pa("utm_source",this.a.sourceTag);b._y=Pa("utm_content",this.a.contentTag);b._z=Pa("utm_term",this.a.termTag);b.im=this.Xb.Gb;this.a.idSync?(c=[],da(new ca,this.a.idSync,c),c=encodeURIComponent(c.join(""))):c="";b._s=c;b.z=Tb(this);
b.C=this.a.mobileApp?1:"";b.KK=a?uc(a):"";a=this.q;c=a.Ta;a.Ta=m;b.l=c?1:"";this.F.ea=0;this.wa(Da()+"//"+this.a.pingServer+"/ping?"+Ra(b))};
n.Sb=function(a){var b=this.a,c=b.playerdomain||this.da;if(na(a.origin)===na(c))if(c=a.data,z(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.nb(a));else if(c=="cbdata?"){var c="&u="+O("u"),d="&t="+O("t"),e="&v="+O("v"),f="&r="+O("r"),b="domain="+encodeURIComponent(b[I])+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b[H])+"&title="+Sb(this)+"&referrer="+U(this)+"&internal="+(Kb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.da)+
c+d+e+f+"&utoken="+this.la;a.source.postMessage(b,"*")}};n.nb=function(a){a[0]==="_demo"&&this.a._demo?this.a._demo=this.a._demo+"%2C"+a[1]:this.a[a[0]]=a[1];this.U=0};function vc(a){a=a.replace(/-{2,}/g,"-");a=Ta(a);a.pathname=N(a.pathname);return a}n.ac=function(a){wc(this,a,"c")};n.bc=function(a){wc(this,a,"r")};
function wc(a,b,c){if(a.Ra&&q()-a.ja>=a.Ja)a.terminate();else{var d=b.href||"",d=vc(d);if(d.protocol.indexOf("http")===0){var e=d.hostname!==o.location.hostname,d=Ua(d),f=$a(b,function(a){return a.id}),h=fc(b,f),j="";a.a.moduleAttribute&&(j=(j=Wa(b,a.a.moduleAttribute))?j.getAttribute(a.a.moduleAttribute):"",j=j.replace(/::/g,"-").substr(0,40));f?(h&&(h="/"+h),h="*[@id='"+f.id+"']"+h,f=fc(b)):f=h;h=ja(h);f=ja(f);b=Vb(b,g,i);c={left:b.x,top:b.y,path:a.a[H],href:d,Wa:h,Ba:f,Va:"",Sa:c,La:0,Nb:a.a[I],
Ka:j};a.ia(c);e||a.q.update("_chartbeat5",xc(c),60,m,g,3,function(a){a=a.split(",");return a[2]+","+a[3]})}}}function uc(a){return[a.left,a.top,a.Wa,encodeURIComponent(a.Va),a.Sa,encodeURIComponent(a.href),a.Ba,a.Ka].join("::")}function xc(a){var b=encodeURIComponent(a.Va),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Wa,b,a.Sa,a.Ba,encodeURIComponent(a.Nb),a.Ka].join(",")}
function tc(a){var b=a.q.k("_chartbeat5");if(!b)return l;var c=b.split("::"),b=c.length,d,e=l,f,h=vc(o.location.href),j=Ua(h);p(c,function(a,b){var c=a.split(","),h=decodeURIComponent(c[3]);if(h){h=za(j,h);if(h===0)return d=c,e=b,m;else if(h===l)return i;if(f===g||h<f)f=h,d=c,e=b}});if(e===l)return l;c.splice(e,1);a.q.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),href:decodeURIComponent(d[3]),
Wa:d[4]||"",Va:"",Ba:d.length>7?d[7]:"",Sa:d.length>6?d[6]:"c",La:b,Ka:d[9]?d[9]:""}}n.terminate=function(){eb(B,this.Db);eb(B,this.Eb);X.M.terminate.call(this)};function yc(a,b){return function(c,d){if(!F){a();var e=o._sf_async_config,f="",h=e[H],h=na(h);/^\//.test(h)&&(f=u(o.location.hostname));e[ub]=Da()+"//"+f+h;if(z(c))e[H]=N(c),d&&(e[J]=d);else if(Ea(c)){var j=["authors","sections",J,H];p(c,function(a,b){if(Fa(j,function(a){return a===b})!==-1||b.indexOf("_")===0)e[b]=b===H?N(a):a})}b()}}};if(!L.k("cb_optout")&&!o.pSUPERFLY){var zc=new X,Y={};o.pSUPERFLY=Y;var Mc=o.pSUPERFLY_mab,$=o.pSUPERFLY_pub,Nc=[];Mc&&Nc.push(Mc);if($)Nc.push($),$.addEngagedAdFilter&&(Y.addEngagedAdFilter=$.addEngagedAdFilter),$.refreshAd&&(Y.refreshAd=$.refreshAd),$.registerGptSlot&&(Y.registerGptSlot=$.registerGptSlot),vb("_cba",function(a){a()});Y.virtualPage=yc(function(){zc.oa();p(Nc,function(a){a.evps()})},function(){zc.ya();p(Nc,function(a){a.svps()})});Y.activity=r(zc.Ab,zc);Nb(zc);var Oc=M.B(i);if(!Oc?
0:Oc.getItem("_cb_ip")){var Pc=o.location;(!/^(.+[.])?chartbeat\.com$/.test(Pc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Pc.pathname))||qc()}else x(o,"message",rc)};})();
